plugins:
 - rubocop-performance
 - rubocop-rspec
 - rubocop-rake

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Metrics/BlockLength:
  Max: 36
  Exclude:
    - spec/**/*.rb

Metrics/BlockNesting:
  Max: 2
  
Layout/LineLength:
  AllowURI: true
  Exclude:
    - ./*.gemspec

Metrics/ClassLength:
  CountComments: false
  Max: 120

Metrics/MethodLength:
  CountComments: false
  Max: 10

Metrics/ParameterLists:
  Max: 4
  CountKeywordArgs: true
  Exclude:
    - ./lib/ruby_lokalise_api/rest/segments.rb

Layout/DotPosition:
  EnforcedStyle: trailing

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: 'no_comma'

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: 'no_comma'

RSpec/MultipleExpectations:
  Max: 30

RSpec/ExampleLength:
  Max: 35

Style/Documentation:
  Enabled: false

RSpec/SpecFilePathFormat:
  CustomTransform:
    OAuth2: oauth2
    OAuth2Client: oauth2_client
    OAuth2Token: oauth2_token
    OAuth2RefreshedToken: oauth2_refreshed_token
  
Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec
  Exclude:
    - ./docs/Gemfile

RSpec/MultipleMemoizedHelpers:
  Exclude:
    - ./spec/lib/ruby_lokalise_api/resources/project_spec.rb