# frozen_string_literal: true

source 'https://rubygems.org'

gem 'jekyll', '~> 4.4'

# gem 'jekyll-theme-minimal', '~> 0.2'
gem 'jekyll-seo-tag', '~> 2.2'

gem 'base64', '~> 0.3'

gem 'kramdown-parser-gfm'

gem 'webrick', '~> 1.8'
