name: CI

on:
  pull_request:

  push:
    branches: [ master ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby:
          - "3.2"
          - "3.3"
          - "3.4"
          - "4.0"
    runs-on: ${{ matrix.os }}
    env:
      LOKALISE_API_TOKEN: 123abc
      OAUTH2_CLIENT_ID: fake
      OAUTH2_CLIENT_SECRET: fake
      OAUTH2_TOKEN: fake
      OAUTH2_REFRESH_TOKEN: fake
      OAUTH2_CODE: fake
      OAUTH2_TOKEN_REFRESHED: fake
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      with:
        persist-credentials: false
    - name: Set up Ruby
      uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rake spec
    - name: Coveralls
      if: matrix.ruby == '4.0'
      uses: coverallsapp/github-action@8d6379e14d29928660c4ba802d8e85393440b329